apiVersion: v1
kind: Service
metadata:
  name: {{ include "1cai-stack.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "1cai-stack.name" . }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "1cai-stack.name" . }}
    app.kubernetes.io/component: api
