apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "observability-stack.fullname" . }}-promtail
  labels:
    app.kubernetes.io/name: {{ include "observability-stack.name" . }}
    app.kubernetes.io/component: promtail
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "observability-stack.name" . }}
      app.kubernetes.io/component: promtail
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "observability-stack.name" . }}
        app.kubernetes.io/component: promtail
    spec:
      serviceAccountName: {{ include "observability-stack.fullname" . }}-promtail
      containers:
        - name: promtail
          image: {{ .Values.promtail.image }}
          args:
            - "-config.file=/etc/promtail/config.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "observability-stack.fullname" . }}-promtail-config
        - name: varlog
          hostPath:
            path: {{ .Values.promtail.hostPath }}
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
