apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability-stack.fullname" . }}-otel-collector
  labels:
    app.kubernetes.io/name: {{ include "observability-stack.name" . }}
    app.kubernetes.io/component: otel-collector
spec:
  replicas: {{ .Values.otelCollector.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "observability-stack.name" . }}
      app.kubernetes.io/component: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "observability-stack.name" . }}
        app.kubernetes.io/component: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image }}
          args:
            - "--config=/etc/otel/otel-config.yaml"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 9464
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /etc/otel
      volumes:
        - name: config
          configMap:
            name: {{ include "observability-stack.fullname" . }}-otel-config
