apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-stack.fullname" . }}-prometheus
  labels:
    app.kubernetes.io/name: {{ include "observability-stack.name" . }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: {{ include "observability-stack.name" . }}
    app.kubernetes.io/component: prometheus
