apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1cai-stack
  namespace: argocd
spec:
  project: 1cai
  source:
    repoURL: https://github.com/DmitrL-dev/1cai.git
    targetRevision: main
    path: infrastructure/helm/1cai-stack
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: 1cai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
